# Generated by Django 5.0.7 on 2024-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('nickname', models.CharField(max_length=15, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('constitution_8', models.CharField(blank=True, choices=[('Hepatonia', '목양'), ('Cholecystonia', '목음'), ('Renotonia', '수양'), ('Vesicotonia', '수음'), ('Pulmotonia', '금양'), ('Colonotonia', '금음'), ('Pancreotonia', '토양'), ('Gastrotonia', '토음')], max_length=50, verbose_name='8체질')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_set', to='users.user')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
