# Generated by Django 5.0.7 on 2024-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_clinic',
            field=models.CharField(blank=True, max_length=15, verbose_name='나의 한의원'),
        ),
    ]
