# Generated by Django 5.0.7 on 2024-08-04 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_appointment_conditionstatus_eatinghabit_delete_event'),
        ('condition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eatinghabit',
            name='user',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment', models.JSONField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condition.condition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ConditionStatus',
        ),
        migrations.DeleteModel(
            name='EatingHabit',
        ),
    ]
