# Generated by Django 5.0.7 on 2024-08-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_remove_conditionstatus_user_remove_eatinghabit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='condition',
        ),
    ]
