# Generated by Django 5.0.7 on 2024-08-03 21:02

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='한의원명')),
                ('detail', models.TextField(verbose_name='한의원 설명')),
                ('location', models.CharField(max_length=50, verbose_name='도로명주소')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('call', models.CharField(max_length=50, verbose_name='전화번호')),
                ('clinic_cate_1', models.CharField(blank=True, choices=[('HealthCare', '건강 관리'), ('Constitution_8', '8체질'), ('Herbal_prescription', '한약 처방'), ('Sasang_constitution', '사상체질'), ('Accident', '교통사고 전문'), ('Acupuncture', '침 치료')], max_length=50, verbose_name='한의원 카테고리 1')),
                ('clinic_cate_2', models.CharField(blank=True, choices=[('HealthCare', '건강 관리'), ('Constitution_8', '8체질'), ('Herbal_prescription', '한약 처방'), ('Sasang_constitution', '사상체질'), ('Accident', '교통사고 전문'), ('Acupuncture', '침 치료')], max_length=50, verbose_name='한의원 카테고리 2')),
                ('clinic_cate_3', models.CharField(blank=True, choices=[('HealthCare', '건강 관리'), ('Constitution_8', '8체질'), ('Herbal_prescription', '한약 처방'), ('Sasang_constitution', '사상체질'), ('Accident', '교통사고 전문'), ('Acupuncture', '침 치료')], max_length=50, verbose_name='한의원 카테고리 3')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=clinic.models.clinic_image_upload_path)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='clinic.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='의료진명')),
                ('image', models.ImageField(upload_to=clinic.models.doctor_image_upload_path)),
                ('profile', models.JSONField(blank=True, verbose_name='약력')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic', verbose_name='한의원 아이디')),
            ],
        ),
    ]
