# Generated by Django 5.0.7 on 2024-08-02 19:15

import clinic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='한의원명')),
                ('detail', models.TextField(verbose_name='한의원 설명')),
                ('location', models.CharField(max_length=50, verbose_name='도로명주소')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lon', models.FloatField(verbose_name='경도')),
                ('call', models.CharField(max_length=50, verbose_name='전화번호')),
                ('clinic_cate', models.CharField(blank=True, choices=[('HealthCare', '건강 관리'), ('Constitution_8', '8체질'), ('Herbal_prescription', '한약 처방'), ('Sasang_constitution', '사상체질'), ('Accident', '교통사고 전문'), ('Acupuncture', '침 치료')], max_length=50, verbose_name='한의원 카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=clinic.models.image_upload_path)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='clinic.clinic')),
            ],
        ),
    ]
