# Generated by Django 5.0.7 on 2024-09-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='식사명')),
                ('date', models.DateField(verbose_name='식사날짜')),
                ('timing', models.CharField(choices=[('morning', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=10, verbose_name='식사시간')),
                ('total', models.IntegerField(default=0, verbose_name='총점')),
                ('ingredients', models.ManyToManyField(related_name='meals', to='meal.ingredient', verbose_name='성분')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
