# Generated by Django 5.0.7 on 2024-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='bad_foods',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='meal',
            name='good_foods',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='meal',
            name='overall_status',
            field=models.CharField(default='soso', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
