# Generated by Django 5.0.7 on 2024-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_meals', to='meal.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_meals', to='meal.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='morning',
            field=models.ManyToManyField(blank=True, related_name='morning_meals', to='meal.menu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='snack',
            field=models.ManyToManyField(blank=True, related_name='snack_meals', to='meal.menu'),
        ),
    ]
