# Generated by Django 5.0.7 on 2024-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_bad_foods_meal_good_foods_meal_overall_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='overall_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
